---
- name: "Create SSL Certs | Yum Install Dependencies"
  become: yes
  yum:
    name:
      - python3-pip
      - python3-devel
      - openssl-devel
      - python3-libselinux
    state: present
  tags:
    - custom_cert

- name: "Create SSL Certs | Update Pip"
  become: yes
  pip:
    name:
      - pip
    state: latest
  tags:
    - custom_cert

- name: "Create SSL Certs | Pip Install Dependencies"
  become: yes
  pip:
    name:
      - cryptography 
      - PyOpenSSL 
      - boto3
    state: latest
  tags:
    - custom_cert

- name: "Create SSL Certs | Create SSL Directory"
  become: yes
  file:
    path: "/etc/{{ gitlab_server_hostname }}/ssl"
    state: directory
    mode: '0775'
  tags:
    - custom_cert

- name: "Create SSL Certs | Generate Private Key"
  become: yes
  openssl_privatekey:
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    select_crypto_backend: cryptography
  when: not letsencrypt_enabled | bool
  tags:
    - custom_cert

- name: "Create SSL Certs | Generate SSL csr"
  become: yes
  openssl_csr:
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.csr"
    privatekey_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    select_crypto_backend: cryptography
    common_name: "{{ gitlab_server_hostname }}{{ domain }}"
  when: not letsencrypt_enabled | bool
  tags:
    - custom_cert

- name: "Create SSL Certs | Generate Self Signed Cert"
  become: yes
  x509_certificate:
    csr_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.csr"
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.crt"
    privatekey_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    selfsigned_version: 3
    provider: selfsigned
  when: not letsencrypt_enabled | bool
  tags:
    - custom_cert

