---
- name: "Create SSL Certs | Yum Install Dependencies"
  become: yes
  yum:
    name:
      - python3-pip
      - python3-devel
      - openssl-devel
      - python3-libselinux
    state: present
  tags:
    - initial_setup

- name: "Create SSL Certs | Update Pip"
  become: yes
  pip:
    name:
      - pip
    state: latest
  tags:
    - initial_setup

- name: "Create SSL Certs | Pip Install Dependencies"
  become: yes
  pip:
    name:
      - cryptography 
      - PyOpenSSL 
    state: latest
  tags:
    - initial_setup

- name: "Create SSL Certs | Create SSL Directory"
  become: yes
  file:
    path: "/etc/{{ gitlab_server_hostname }}/ssl"
    state: directory
    mode: '0775'
  tags:
    - initial_setup

- name: "Create SSL Certs | Generate Private Key"
  become: yes
  openssl_privatekey:
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    select_crypto_backend: cryptography
  tags:
    - initial_setup

- name: "Create SSL Certs | Generate SSL csr"
  become: yes
  openssl_csr:
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.csr"
    privatekey_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    select_crypto_backend: cryptography
    common_name: "{{ gitlab_server_hostname }}{{ domain }}"
  tags:
    - initial_setup

- name: "Create SSL Certs | Generate Self Signed Cert"
  become: yes
  x509_certificate:
    csr_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.csr"
    path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.crt"
    privatekey_path: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    selfsigned_version: 3
    provider: selfsigned
  tags:
    - initial_setup

- name: "Create SSL Certs | Copy SSL Certs to {{ gitlab_service_account }} Home"
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/home/{{ gitlab_service_account }}/"
    owner: "{{ gitlab_service_account }}"
    group: "{{ gitlab_service_account }}"
    remote_src: yes
  with_items:
    - "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.pem"
    - "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.crt"
  tags:
    - initial_setup

- name: "Create SSL Certs | Generate Let's Encrypt Cert"
  become: yes
  acme_certificate:
    account_key_src: "/etc/{{ gitlab_server_hostname }}/ssl/account.key"
    csr: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.csr"
    dest: "/etc/{{ gitlab_server_hostname }}/ssl/{{ gitlab_server_hostname }}{{ domain }}.crt"
    challenge: http-01
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    terms_agreed: yes
  when: letsencrypt_enabled
  tags:
    - initial_setup

