---
- name: "Gitlab Management | Restart {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gitlab_service_account_uid }}"
  systemd:
    name: "container-{{ gitlab_server_name }}.service"
    state: restarted
    daemon_reload: yes
    scope: user
  tags:
    - restart_gitlab

- name: "Gitlab Management | Stop {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gitlab_service_account_uid }}"
  systemd:
    name: "container-{{ gitlab_server_name }}.service"
    state: stopped
    daemon_reload: yes
    scope: user
  ignore_errors: true
  tags:
    - stop_gitlab
    - remove_gitlab
    - destroy_gitlab

- name: "Gitlab Management | Remove {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  podman_container:
    name: "{{ gitlab_server_name }}"
    state: absent
  ignore_errors: true
  tags:
    - remove_gitlab
    - destroy_gitlab
    - delete_gitlab

- name: "Gitlab Management | Remove {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  podman_volume:
    name: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - git_app_data
    - git_logs
    - git_config_data
  tags:
    - destroy_gitlab
    - remove_gitlab
    
- name: "Remove GitLab systemd service file"
  become_user: "{{ gitlab_service_account }}"
  file:
    path: "/home/{{ gitlab_service_account }}/.config/systemd/user/container-{{ gitlab_server_name }}.service"
    state: absent
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: Remove SSL Certs directory for GitLab
  become: yes
  file:
    path: "/etc/{{ gitlab_server_hostname }}/ssl/"
    state: absent
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab
    
- name: "Reload systemd daemon after removing GitLab service"
  become_user: "{{ gitlab_service_account }}"
  shell: "systemctl daemon-reload"
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab


- name: "PostgreSQL Management | Stop PostgreSQL Container"
  become: yes
  become_user: "{{ postgres_service_account }}"
  podman_container:
    name: "postgres"
    state: stopped
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "PostgreSQL Management | Remove PostgreSQL Container"
  become: yes
  become_user: "{{ postgres_service_account }}"
  podman_container:
    name: "postgres"
    state: absent
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "PostgreSQL Management | Remove PostgreSQL Data Volume"
  become: yes
  become_user: "{{ postgres_service_account }}"
  podman_volume:
    name: "/srv/postgresql/data"
    state: absent
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "PostgreSQL Management | Reload systemd daemon after removing PostgreSQL service"
  become_user: "{{ postgres_service_account }}"
  shell: "systemctl daemon-reload"
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "PostgreSQL Management | Remove PostgreSQL volume"
  become_user: "{{ postgres_service_account }}"
  shell: "podman volume rm postgresql"
  ignore_errors: true
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "Destroy GitLab network"
  podman_network:
    name: gitlab_network
    state: absent
  become_user: "{{ gitlab_service_account }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gitlab_service_account_uid }}"
  tags:
    - remove_gitlab
    - destroy_gitlab