---
- name: "Gitlab Management | Restart {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gitlab_service_account_uid }}"
  systemd:
    name: "container-{{ gitlab_server_name }}.service"
    state: restarted
    daemon_reload: yes
    scope: user
  tags:
    - restart_gitlab

- name: "Gitlab Management | Stop {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gitlab_service_account_uid }}"
  systemd:
    name: "container-{{ gitlab_server_name }}.service"
    state: stopped
    daemon_reload: yes
    scope: user
  tags:
    - stop_gitlab
    - remove_gitlab
    - destroy_gitlab

- name: "Gitlab Management | Remove {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  podman_container:
    name: "{{ gitlab_server_name }}"
    state: absent
  tags:
    - remove_gitlab
    - destroy_gitlab
    - delete_gitlab

- name: "Gitlab Management | Remove {{ gitlab_server_name }} Container"
  become: yes
  become_user: "{{ gitlab_service_account }}"
  podman_volume:
    name: "{{ item }}"
    state: absent
  with_items:
    - git_app_data
    - git_logs
    - git_config_data
  tags:
    - destroy_gitlab
    - remove_gitlab
    
- name: "Stop and disable GitLab systemd service if it exists"
  become_user: "{{ gitlab_service_account }}"
  systemd:
    name: "container-{{ gitlab_server_name }}.service"
    state: stopped
    enabled: no
  when: gitlab_service_status.status is defined and gitlab_service_status.status == "running"
  tags:
    - destroy_gitlab
    - remove_gitlab
- name: "Remove GitLab systemd service file"
  become_user: "{{ gitlab_service_account }}"
  file:
    path: "/home/{{ gitlab_service_account }}/.config/systemd/user/container-{{ gitlab_server_name }}.service"
    state: absent
  tags:
    - destroy_gitlab
    - remove_gitlab

- name: "Reload systemd daemon after removing GitLab service"
  become_user: "{{ gitlab_service_account }}"
  shell: "systemctl --user daemon-reload"
  tags:
    - destroy_gitlab
    - remove_gitlab
